### ISSUE TITLE
Nagios check failure

### ISSUE THREAD

**Issue by Brickius** [PureStorage-OpenConnect/Monitoring#8]
Getting the following error when running in Nagios-

`(No output on stdout) stderr: Traceback (most recent call last):
File "/usr/local/nagios/libexec/check_purefa_alert.py", line 40, in 
import purestorage
File "/usr/lib/python2.6/site-packages/purestorage/__init__.py", line 1, in 
from .purestorage import FlashArray, PureError, PureHTTPError, VERSION
File "/usr/lib/python2.6/site-packages/purestorage/purestorage.py", line 11, in 
import requests
File "/usr/lib/python2.6/site-packages/requests/__init__.py", line 114, in 
from .models import Request, Response, PreparedRequest
File "/usr/lib/python2.6/site-packages/requests/models.py", line 655
return {attr: getattr(self, attr, None) for attr in self.__attrs__}
^
SyntaxError: invalid syntax`

Any ideas whats wrong here?

**Comment by Brickius** [comment]
I get-

`Python 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import purestorage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named purestorage
`
